FROM golang:1.23-alpine

# Install required packages
RUN apk add --no-cache git curl

# Install Air (live reload tool)
RUN go install github.com/cosmtrek/air@v1.40.4

# Set working directory
WORKDIR /go/src/app

# Copy go.mod and go.sum early to cache deps
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Expose the app port
EXPOSE 8080

# Run the app with Air
CMD ["air"]
